import sqlite3
conn = sqlite3.connect('dev.db')
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='broker_accounts'")
result = cursor.fetchone()
print('Table exists' if result else 'Table does not exist')
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
tables = cursor.fetchall()
print('All tables:', [t[0] for t in tables])
conn.close()